"""PreToolUse gate for Write / Edit / MultiEdit / NotebookEdit.

Two rules, either of which can deny a write. Both stand only where this gate
stands at all: ``enforce_spec_before_code`` is on and the project has a
``spec/`` directory. Anywhere else every write is allowed.

**The approval record is not written through a tool.**
``.gatekit/approvals.json`` holds what the user approved. The ``gatekit.py
approve`` process writes it — ``/gatekit-gate`` runs that command after the
user said yes — and a process does not pass through this hook. A Write or an
Edit aimed at the file is therefore denied, before approval and after it:
written by hand before approval it opens the code lock without the user, and
nothing has a reason to edit it afterwards.

**Spec before code.** Code stays locked until a human has approved
``spec/05-gate.md`` (a hash-anchored approval, see :mod:`gatekit.approval`).
Documentation and the spec set itself stay writable throughout, otherwise there
would be no way to produce the spec that unlocks the gate.

The shell gates (:mod:`gatekit.gates.bash`, :mod:`gatekit.gates.powershell`)
hand every file a command would write to :func:`decide_path`, so a shell write
meets the same two rules — while code is locked. Once the gate is approved they
do not read commands at all (:func:`restrictions_active`).

**Paths are compared without regard to case** (ADR-0022). The kit is
Windows-only and the file system is case-insensitive: ``SRC/Auth/x.ts`` and
``src/auth/x.ts`` are one file, so they get one verdict. The fold is applied to
both sides of every comparison in this module (:func:`matches`,
:func:`in_allowlist`, :func:`is_approval_record`), so no spelling of a path
reaches a rule its lower-case spelling would not reach.

Denial reasons are written in the session's ``output_lang``.
"""
from __future__ import annotations

import fnmatch
import pathlib
from typing import Any, Dict, List, Optional

if __name__ == "__main__" or __package__ in (None, ""):  # pragma: no cover
    from _bootstrap import ensure_package_path

    ensure_package_path()
else:
    from ._bootstrap import ensure_package_path

    ensure_package_path()

from gatekit import approval, config, hookio, ledger, paths  # noqa: E402

#: Paths that stay writable while code is locked, so the spec can be authored at all.
SPEC_ALLOWLIST = (
    "spec/**",
    ".gatekit/**",
    "docs/**",
    "README*",
    "*.md",  # root-level markdown only; the pattern is matched without '/'
)

GATE_TARGET = "spec/05-gate.md"

#: The approval record, relative to the project root: ``.gatekit/approvals.json``.
#: Inside the allowlist's ``.gatekit/**``, so it is judged before the allowlist.
APPROVAL_RECORD = paths.approvals_file(pathlib.Path()).as_posix()

_MESSAGES = {
    "en": {
        "spec_first": (
            "gatekit: writing code is blocked until spec/05-gate.md is approved "
            "(current status: {status}). Run the /gatekit-gate pipeline and have "
            "the user approve the gate, or write to spec/, docs/ or *.md first. "
            "Blocked path: {path}"
        ),
        "approval_record": (
            "gatekit: .gatekit/approvals.json is the approval record and is not "
            "written by hand. The user decides an approval and /gatekit-gate "
            "records it with the approve command. Do not edit this file: when an "
            "approval is needed, go back to /gatekit-gate and ask the user. "
            "Blocked path: {path}"
        ),
    },
    "ko": {
        "spec_first": (
            "gatekit: spec/05-gate.md 승인 전에는 코드를 쓸 수 없습니다 "
            "(현재 상태: {status}). /gatekit-gate 파이프라인을 실행해 사용자 승인을 "
            "받거나, 먼저 spec/·docs/·*.md 에 작성하세요. 차단된 경로: {path}"
        ),
        "approval_record": (
            "gatekit: .gatekit/approvals.json 은 승인 기록이라 직접 쓰거나 고칠 수 "
            "없습니다. 승인은 사용자가 정하고, /gatekit-gate 가 approve 명령으로 "
            "기록합니다. 이 파일을 직접 고치지 말고, 승인이 필요하면 /gatekit-gate 로 "
            "돌아가 사용자에게 승인받으세요. 차단된 경로: {path}"
        ),
    },
}


def _message(lang: str, key: str, **fields: Any) -> str:
    table = _MESSAGES.get(lang, _MESSAGES["en"])
    return table.get(key, _MESSAGES["en"][key]).format(**fields)


def target_path(tool_input: Dict[str, Any]) -> str:
    """Extract the path a write tool is about to touch.

    ``NotebookEdit`` uses ``notebook_path``; the other three use ``file_path``.
    """
    if not isinstance(tool_input, dict):
        return ""
    for key in ("file_path", "notebook_path"):
        value = tool_input.get(key)
        if isinstance(value, str) and value.strip():
            return value
    return ""


def relative_target(root: pathlib.Path, raw_path: str) -> Optional[str]:
    """Normalize *raw_path* to a POSIX path relative to *root*.

    Returns ``None`` when the target lies outside the project root. Relative
    inputs are resolved against the root, and symlinks are resolved so a link
    cannot be used to land outside the project.
    """
    candidate = pathlib.Path(raw_path)
    if not candidate.is_absolute():
        candidate = pathlib.Path(root) / candidate
    return paths.relative_to_root(root, candidate)


def fold(text: str) -> str:
    """The form in which paths and patterns are compared: lower case.

    Done explicitly instead of through ``fnmatch.fnmatch`` (which folds only
    on a Windows interpreter), so the verdict does not depend on where the
    code runs.
    """
    return text.lower()


def matches(relpath: str, pattern: str) -> bool:
    """Glob match with ``**`` crossing directory separators.

    ``fnmatch`` alone treats ``*`` as crossing ``/``, which would make
    ``src/auth/*.ts`` match a nested file. This translates the pattern so that
    ``*`` stays within one path segment while ``**`` spans any number.

    Case is ignored on both sides (:func:`fold`): the path and the pattern
    name files on a case-insensitive file system.

    A bracket is a letter, not a character set: ``src/app/[id]/page.tsx`` names
    the folder ``[id]`` (the route folders of Next.js and its kin), and reading
    it as "one of i, d" refused that very file while allowing ``src/app/i/``.
    """
    relpath = fold(relpath)
    pattern = fold(pattern.strip().replace("\\", "/"))
    while pattern.startswith("./"):
        pattern = pattern[2:]
    if not pattern:
        return False

    # A bare "**" or a "dir/**" prefix should also match the directory itself.
    if pattern.endswith("/**") and relpath == pattern[:-3]:
        return True
    if pattern == "**":
        return True

    return _glob_match(relpath.split("/"), pattern.split("/"))


def _glob_match(parts: List[str], pats: List[str]) -> bool:
    """Segment-wise match where a ``**`` segment consumes any number of parts."""
    if not pats:
        return not parts
    head, rest = pats[0], pats[1:]
    if head == "**":
        if not rest:
            return True
        for index in range(len(parts) + 1):
            if _glob_match(parts[index:], rest):
                return True
        return False
    if not parts:
        return False
    if not fnmatch.fnmatchcase(parts[0], head.replace("[", "[[]")):
        return False
    return _glob_match(parts[1:], rest)


def in_allowlist(relpath: str) -> bool:
    """True when *relpath* is writable regardless of the spec gate.

    Case-insensitive like :func:`matches`: ``SPEC/x.md``, ``Docs/a.md`` and
    ``readme.MD`` are the same files as their usual spellings.
    """
    relpath = fold(relpath)
    for pattern in SPEC_ALLOWLIST:
        if pattern == "*.md":
            # Root-level markdown only: no separator left in the path.
            if "/" not in relpath and fnmatch.fnmatchcase(relpath, "*.md"):
                return True
            continue
        if pattern == "README*":
            if "/" not in relpath and fnmatch.fnmatchcase(relpath, fold("README*")):
                return True
            continue
        if matches(relpath, pattern):
            return True
    return False


def is_approval_record(relpath: str) -> bool:
    """True when *relpath* (relative to the project root) names the approval record.

    The name is compared the way Windows opens it: case is ignored, the dots
    and spaces that end a name are dropped (``approvals.json.`` creates
    ``approvals.json``, measured) and ``name::$DATA`` is the file's own
    content. ``realpath`` restores such a spelling only for a file that
    exists, and before the first approval this one does not.
    """
    parts = fold(relpath).split("/")
    parts[-1] = parts[-1].split(":", 1)[0]
    return "/".join(part.rstrip(" .") for part in parts) == fold(APPROVAL_RECORD)


def restrictions_active(root: pathlib.Path) -> bool:
    """True while code is locked: a spec set exists and its gate is not approved.

    Lets a caller that must parse its input (the shell gates) skip the parse
    entirely when the code lock could deny nothing. The approval-record rule
    does not count here, on purpose: it alone would make the shell gates read
    every command of an approved project, and a command they cannot read would
    then be refused where it passes today.
    """
    cfg = config.load(root)
    if not cfg.get("enforce_spec_before_code", True):
        return False
    if not paths.spec_dir(root).is_dir():
        return False
    return approval.check(root, GATE_TARGET) != "ok"


def decide_path(root: pathlib.Path, raw_path: str, lang: str) -> Optional[Dict[str, Any]]:
    """Judge one target path: the approval record, then spec before code.

    Returns a deny payload, or ``None`` to allow. Shared by the Write gate and
    the shell gates so a shell redirect is judged exactly like a Write call.
    """
    relpath = relative_target(root, raw_path)

    cfg = config.load(root)
    if not cfg.get("enforce_spec_before_code", True):
        return hookio.allow()
    if not paths.spec_dir(root).is_dir():
        return hookio.allow()

    # -- the approval record: denied whatever the approval status is -------
    # Checked before the allowlist, whose ".gatekit/**" would let it through.
    if relpath is not None and is_approval_record(relpath):
        return hookio.deny(_message(lang, "approval_record", path=relpath))

    # -- spec before code ---------------------------------------------------
    if relpath is not None and in_allowlist(relpath):
        return hookio.allow()

    status = approval.check(root, GATE_TARGET)
    if status == "ok":
        return hookio.allow()

    return hookio.deny(
        _message(lang, "spec_first", status=status, path=relpath or raw_path)
    )


def session_lang(root: pathlib.Path, event: Dict[str, Any]) -> str:
    """Read the session's output language, defaulting to Korean."""
    try:
        return ledger.Ledger.load(root, hookio.session_id(event)).output_lang
    except Exception:  # noqa: BLE001 - language must never break the gate
        return "ko"


def handle(event: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Decide whether this write may proceed."""
    root = hookio.event_root(event)
    tool_input = event.get("tool_input") or {}

    raw_path = target_path(tool_input)
    if not raw_path:
        return hookio.allow()
    return decide_path(root, raw_path, session_lang(root, event))


def main() -> None:  # pragma: no cover - exercised via subprocess tests
    hookio.run(handle)


if __name__ == "__main__":  # pragma: no cover
    main()
